### ISSUE TITLE
Unicode close double quote symbol causes exception

### ISSUE THREAD

**Issue by arganoid** [fkirc/bitbucket-issues-to-github#1]
Presence of a close double quote symbol U+201D - ” - in db-1.0.json, causes this error:

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 336: character maps to <undefined>

Error occurs in IncrementalDecoder.decode, called from line 33: json_object = json.loads(f.read())

**Comment by fkirc** [comment]
If you change this line to:

`json_object = json.load(f)`

Does this solve the problem?

**Comment by arganoid** [comment]
No, same error.

**Comment by fkirc** [comment]
Can you provide a sample `db-1.0.json` to reproduce this issue?

**Comment by arganoid** [comment]
{"milestones":[],"attachments":[],"versions":[],"comments":[],"meta":{"default_milestone":null,"default_assignee":null,"default_kind":"bug","default_component":null,"default_version":null},"components":[],"issues":[{"status":"new","priority":"major","kind":"bug","content_updated_on":null,"voters":[],"title":"”","reporter":"arganoid","component":null,"watchers":["arganoid"],"content":"Test","assignee":null,"created_on":"2020-01-11T21:26:33.983169+00:00","version":null,"edited_on":null,"milestone":null,"updated_on":"2020-01-11T21:26:33.983169+00:00","id":1}],"logs":[]}

**Comment by fkirc** [comment]
I see that `"title":"”"` contains a "Right Double Quotation Mark", which is the 3-byte unicode symbol `”` with hex `E2 80 9D`.

However, this parsing error does not reproduce on my Ubuntu 18.04 with Python 3.6.9.
Which Python version and OS are you using?

**Comment by arganoid** [comment]
Windows 10, Python 3.7.5

**Comment by fkirc** [comment]
Fixed with 377a0622075c66aa94b5fc42a2cf54bae204db33.
Thank you for reporting.
