### ISSUE TITLE
Issue attachments

### ISSUE THREAD

**Issue by fpoli** [fkirc/bitbucket-issues-to-github#3]
Are there any plans (or suggestions) regarding how to migrate the attachments of BitBucket issues?

**Comment by fkirc** [comment]
I do not currently have any plans to do this.
Nevertheless, I would be happy to take a CI-tested Pull Request that does this.

**Comment by fkirc** [comment]
Closing this issue because of new project-policies:
Additional features are only done for "one-off-contracts", unless it is a really trivial feature.
